# Generated by Django 6.0 on 2025-12-08 05:58

import django.db.models.deletion
import regulations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Regulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='사규코드')),
                ('title', models.CharField(max_length=200, verbose_name='사규명')),
                ('category', models.CharField(choices=[('POLICY', '정책/방침'), ('REGULATION', '규정'), ('GUIDELINE', '지침'), ('MANUAL', '매뉴얼/가이드라인')], max_length=20, verbose_name='분류')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='의무준수')),
                ('scope', models.CharField(choices=[('ALL', '전 임직원'), ('DEPT', '소속부서')], default='ALL', max_length=10, verbose_name='적용범위')),
                ('current_version', models.CharField(default='1.0', max_length=10, verbose_name='현재버전')),
                ('status', models.CharField(choices=[('DRAFT', '초안'), ('REVIEW', '검토중'), ('ACTIVE', '시행중'), ('ABOLISHED', '폐지')], default='DRAFT', max_length=20, verbose_name='상태')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='시행일')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='정기검토예정일')),
                ('abolished_date', models.DateField(blank=True, null=True, verbose_name='폐지일')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_regulations', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('parent_regulation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_regulations', to='regulations.regulation', verbose_name='상위사규')),
                ('related_regulations', models.ManyToManyField(blank=True, to='regulations.regulation', verbose_name='관련사규')),
                ('responsible_dept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regulations', to='accounts.department', verbose_name='책임부서')),
            ],
            options={
                'verbose_name': '사규',
                'verbose_name_plural': '사규',
                'ordering': ['category', 'code'],
            },
        ),
        migrations.CreateModel(
            name='RegulationTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='태그명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('regulations', models.ManyToManyField(blank=True, related_name='tags', to='regulations.regulation', verbose_name='사규')),
            ],
            options={
                'verbose_name': '태그',
                'verbose_name_plural': '태그',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RegulationVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(max_length=10, verbose_name='버전번호')),
                ('change_type', models.CharField(choices=[('CREATE', '제정'), ('REVISE', '개정'), ('ABOLISH', '폐지')], max_length=10, verbose_name='변경유형')),
                ('change_reason', models.TextField(verbose_name='변경사유')),
                ('change_summary', models.TextField(blank=True, verbose_name='변경내용요약')),
                ('content_file', models.FileField(blank=True, null=True, upload_to=regulations.models.regulation_file_path, verbose_name='첨부파일')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='승인일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_versions', to=settings.AUTH_USER_MODEL, verbose_name='승인자')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_versions', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('regulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='regulations.regulation', verbose_name='사규')),
            ],
            options={
                'verbose_name': '사규 버전',
                'verbose_name_plural': '사규 버전',
                'ordering': ['-created_at'],
                'unique_together': {('regulation', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='RegulationDownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 주소')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True, verbose_name='다운로드일시')),
                ('regulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_logs', to='regulations.regulation', verbose_name='사규')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='download_logs', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_logs', to='regulations.regulationversion', verbose_name='버전')),
            ],
            options={
                'verbose_name': '다운로드 로그',
                'verbose_name_plural': '다운로드 로그',
                'ordering': ['-downloaded_at'],
            },
        ),
    ]
