# Generated by Django 6.0 on 2025-12-11 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulation',
            name='reference_url',
            field=models.URLField(blank=True, help_text='사규 원문 링크', null=True, verbose_name='참조링크'),
        ),
    ]
