# Generated by Django 6.0 on 2025-12-11 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0002_regulation_reference_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulation',
            name='group',
            field=models.CharField(blank=True, help_text='소속 그룹 또는 조직', max_length=100, verbose_name='그룹'),
        ),
        migrations.AddField(
            model_name='regulation',
            name='is_public',
            field=models.BooleanField(default=True, help_text='임직원에게 공개 여부', verbose_name='임직원 공개'),
        ),
        migrations.AddField(
            model_name='regulation',
            name='manager',
            field=models.CharField(blank=True, help_text='담당자 이름 또는 연락처', max_length=100, verbose_name='담당자'),
        ),
    ]
