# Generated by Django 6.0 on 2025-12-11 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0003_regulation_group_regulation_is_public_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', '결재대기'), ('APPROVING', '결재중'), ('APPROVED', '승인완료'), ('REJECTED', '반려'), ('CANCELLED', '취소')], default='PENDING', max_length=20, verbose_name='결재상태')),
                ('request_reason', models.TextField(help_text='결재를 요청하는 사유를 입력하세요', verbose_name='결재사유')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='요청일시')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료일시')),
                ('rejection_reason', models.TextField(blank=True, help_text='반려 시 사유를 입력하세요', verbose_name='반려사유')),
                ('regulation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='regulations.regulation', verbose_name='사규')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_approvals', to=settings.AUTH_USER_MODEL, verbose_name='요청자')),
            ],
            options={
                'verbose_name': '결재',
                'verbose_name_plural': '결재',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(help_text='결재 순서 (1부터 시작)', verbose_name='순서')),
                ('status', models.CharField(choices=[('PENDING', '대기'), ('APPROVED', '승인'), ('REJECTED', '반려')], default='PENDING', max_length=20, verbose_name='상태')),
                ('comment', models.TextField(blank=True, verbose_name='의견')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='결재일시')),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_lines', to='regulations.approval', verbose_name='결재')),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_lines', to=settings.AUTH_USER_MODEL, verbose_name='결재자')),
            ],
            options={
                'verbose_name': '결재 라인',
                'verbose_name_plural': '결재 라인',
                'ordering': ['approval', 'sequence'],
                'unique_together': {('approval', 'sequence')},
            },
        ),
    ]
