# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0004_approval_approvalline'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalline',
            name='role_name',
            field=models.CharField(blank=True, help_text='결재자의 역할 (예: 부문장, 준법지원인)', max_length=50, verbose_name='역할명'),
        ),
    ]

