# Generated by Django 6.0 on 2025-12-11 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0004_approval_approvalline'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalline',
            name='role_name',
            field=models.CharField(max_length=50, verbose_name='역할명', default=''),
            preserve_default=False,
        ),
    ]
