# Generated by Django 6.0 on 2025-12-11 08:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_company_department_company_user_company'),
        ('regulations', '0005_approvalline_role_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='regulation',
            name='access_level',
            field=models.CharField(choices=[('ALL', '전체 직원'), ('COMPANY', '지정된 법인'), ('DEPARTMENT', '지정된 부서'), ('EMPLOYEE', '지정된 직원')], default='ALL', help_text='이 사규에 접근할 수 있는 대상을 지정합니다', max_length=20, verbose_name='접근 권한'),
        ),
        migrations.AddField(
            model_name='regulation',
            name='allowed_companies',
            field=models.ManyToManyField(blank=True, help_text='접근 권한이 "지정된 법인"인 경우 선택', related_name='accessible_regulations', to='accounts.company', verbose_name='접근 가능 법인'),
        ),
        migrations.AddField(
            model_name='regulation',
            name='allowed_departments',
            field=models.ManyToManyField(blank=True, help_text='접근 권한이 "지정된 부서"인 경우 선택', related_name='accessible_regulations', to='accounts.department', verbose_name='접근 가능 부서'),
        ),
        migrations.AddField(
            model_name='regulation',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, help_text='접근 권한이 "지정된 직원"인 경우 선택', related_name='accessible_regulations', to=settings.AUTH_USER_MODEL, verbose_name='접근 가능 직원'),
        ),
        migrations.AlterField(
            model_name='approvalline',
            name='role_name',
            field=models.CharField(blank=True, help_text='결재자의 역할 (예: 부문장, 준법지원인)', max_length=50, verbose_name='역할명'),
        ),
    ]
