# Generated by Django 6.0 on 2025-12-12 07:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_company_department_company_user_company'),
        ('regulations', '0006_regulation_access_level_regulation_allowed_companies_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulation',
            name='access_level',
            field=models.CharField(choices=[('ALL', '전체 직원'), ('COMPANIES', '지정된 법인'), ('DEPARTMENTS', '지정된 부서'), ('USERS', '지정된 직원')], default='ALL', help_text='사규 접근 권한 설정', max_length=20, verbose_name='접근 권한'),
        ),
        migrations.AlterField(
            model_name='regulation',
            name='allowed_companies',
            field=models.ManyToManyField(blank=True, related_name='accessible_regulations', to='accounts.company', verbose_name='허용된 법인'),
        ),
        migrations.AlterField(
            model_name='regulation',
            name='allowed_departments',
            field=models.ManyToManyField(blank=True, related_name='accessible_regulations', to='accounts.department', verbose_name='허용된 부서'),
        ),
        migrations.AlterField(
            model_name='regulation',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='accessible_regulations', to=settings.AUTH_USER_MODEL, verbose_name='허용된 직원'),
        ),
    ]
