# Generated by Django 6.0 on 2026-01-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0007_alter_regulation_access_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulation',
            name='content',
            field=models.TextField(blank=True, help_text='사규의 본문 내용', verbose_name='규정 본문'),
        ),
        migrations.AlterField(
            model_name='regulation',
            name='access_level',
            field=models.CharField(choices=[('ALL', '전체 직원'), ('DEPARTMENTS', '지정된 부서'), ('USERS', '지정된 직원')], default='ALL', help_text='사규 접근 권한 설정', max_length=20, verbose_name='접근 권한'),
        ),
        migrations.AlterField(
            model_name='regulation',
            name='status',
            field=models.CharField(choices=[('ACTIVE', '시행중'), ('ABOLISHED', '폐지')], default='ACTIVE', max_length=20, verbose_name='상태'),
        ),
    ]
