# Generated by Django 6.0 on 2026-01-07 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0008_add_content_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('regulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='regulations.regulation', verbose_name='사규')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '즐겨찾기',
                'verbose_name_plural': '즐겨찾기',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'regulation')},
            },
        ),
    ]
