# Generated by Django 6.0 on 2026-01-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0009_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulation',
            name='original_file',
            field=models.FileField(blank=True, help_text='사규 원본 파일 (PDF, Word, HWP 등)', null=True, upload_to='regulations/original/', verbose_name='사규 원본 파일'),
        ),
    ]
