# Generated by Django 6.0 on 2026-01-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0010_regulation_original_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulation',
            name='manager_primary',
            field=models.CharField(blank=True, help_text='사규관리자 정 (이름)', max_length=100, verbose_name='사규관리자(정)'),
        ),
        migrations.AddField(
            model_name='regulation',
            name='manager_secondary',
            field=models.CharField(blank=True, help_text='사규관리자 부 (이름)', max_length=100, verbose_name='사규관리자(부)'),
        ),
    ]
