# Generated by Django 6.0 on 2026-01-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0011_regulation_manager_primary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regulation',
            name='manager_secondary',
        ),
        migrations.AlterField(
            model_name='regulation',
            name='manager',
            field=models.CharField(blank=True, help_text='사규관리 담당자 이름', max_length=100, verbose_name='사규관리 담당자'),
        ),
        migrations.AlterField(
            model_name='regulation',
            name='manager_primary',
            field=models.CharField(blank=True, help_text='사규관리 책임자 이름', max_length=100, verbose_name='사규관리 책임자'),
        ),
    ]
