# Generated by Django 6.0 on 2026-01-07 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0012_remove_regulation_manager_secondary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_type', models.CharField(choices=[('GROUP', '그룹'), ('CATEGORY', '분류'), ('STATUS', '상태'), ('SCOPE', '적용범위'), ('ACCESS_LEVEL', '접근권한'), ('CHANGE_TYPE', '변경유형'), ('CUSTOM', '사용자정의')], help_text='코드의 유형을 선택하세요', max_length=20, verbose_name='코드유형')),
                ('code', models.CharField(help_text='시스템에서 사용되는 코드 값', max_length=50, verbose_name='코드')),
                ('name', models.CharField(help_text='화면에 표시되는 이름', max_length=100, verbose_name='코드명')),
                ('description', models.TextField(blank=True, help_text='코드에 대한 상세 설명', verbose_name='설명')),
                ('sort_order', models.IntegerField(default=0, help_text='목록 표시 순서 (작은 숫자가 먼저 표시)', verbose_name='정렬순서')),
                ('is_active', models.BooleanField(default=True, help_text='체크 해제 시 선택 목록에서 숨김', verbose_name='사용여부')),
                ('is_system', models.BooleanField(default=False, help_text='시스템 코드는 삭제할 수 없습니다', verbose_name='시스템코드')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('parent', models.ForeignKey(blank=True, help_text='계층 구조가 필요한 경우 상위 코드 지정', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='regulations.commoncode', verbose_name='상위코드')),
            ],
            options={
                'verbose_name': '공통코드',
                'verbose_name_plural': '공통코드',
                'ordering': ['code_type', 'sort_order', 'code'],
                'unique_together': {('code_type', 'code')},
            },
        ),
    ]
