# Generated by Django 6.0 on 2025-12-08 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regulations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('CHANGE', '제개정알림'), ('EXPIRY', '만료예정알림'), ('REVIEW', '검토요청알림'), ('SYSTEM', '시스템알림')], max_length=20, verbose_name='알림유형')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('message', models.TextField(verbose_name='내용')),
                ('is_read', models.BooleanField(default=False, verbose_name='읽음여부')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='읽은시간')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('regulation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='regulations.regulation', verbose_name='관련사규')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='수신자')),
            ],
            options={
                'verbose_name': '알림',
                'verbose_name_plural': '알림',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_change_notification', models.BooleanField(default=True, verbose_name='제개정알림수신')),
                ('receive_expiry_notification', models.BooleanField(default=True, verbose_name='만료예정알림수신')),
                ('receive_review_notification', models.BooleanField(default=True, verbose_name='검토요청알림수신')),
                ('email_notification', models.BooleanField(default=False, verbose_name='이메일알림')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_setting', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '알림 설정',
                'verbose_name_plural': '알림 설정',
            },
        ),
    ]
