# Generated by Django 6.0 on 2026-01-08 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='batch_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='같은 발송 건을 식별하는 ID', null=True, verbose_name='발송ID'),
        ),
    ]
